version: '3'
services:
  sqldata:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=SaPass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  nginx:
    image: sadmins/nginx
    ports:
      - "80:80"

  dpa:
    image: sadmins/dpa
    ports:
      - "8123:8123"
    stdin_open: true
